### PR TITLE
Add interactive football pitch example

### PR DESCRIPTION
**Pull request by seidlr**
Added my interactive football pitch voila example.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @seidlr, I remember you shared it on Gitter too!

It looks like the repo has both an `environment.yml` and a `requirements.txt` files with the same dependencies. Maybe worth only keeping `environment.yml` to keep things simple and avoid confusion?

**Comment by jtpio** [comment]
Also we are looking into getting one more change in before adding new examples to the gallery.

**Comment by seidlr** [comment]
I could delete the file but I think the `requirements.txt` was needed for heroku deployment. Is it possible to add a reference to a branch in `gallery.yaml`?

**Comment by yuvipanda** [comment]
If you have both files, repo2docker will *only* count the environment.yml file, so I think it's ok...

**Comment by jtpio** [comment]
Ah ok, then it makes sense to keep both for Heroku.

**Review by jtpio — APPROVED** [review]

**Comment by jtpio** [comment]
Thanks @seidlr!

**Pull request merged**
