### PR TITLE
add 'machine-learning-visualization' to gallery.yaml

### PR DESCRIPTION
**Pull request by dhaitz**

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @dhaitz!

I think it would also be great to add a Binder badge to the repo. That would point to:
https://mybinder.org/v2/gh/dhaitz/machine-learning-interactive-visualization/master?urlpath=voila%2Frender%2Fmachine-learning-interactive-visualization.ipynb

Or to a pinned version: https://mybinder.org/v2/gh/dhaitz/machine-learning-interactive-visualization/0dc76c5647aa2161770a30efd265b1af66254982?urlpath=voila%2Frender%2Fmachine-learning-interactive-visualization.ipynb

Similar to the [country-indicator](https://github.com/voila-gallery/voila-gallery-country-indicators/blob/master/README.md) example.

**Comment by jtpio** [comment]
Also there seems to be an issue with the dependencies when trying it on Binder:

```
AttributeError: module 'ipywidgets' has no attribute 'GridspecLayout'
```

It's relevant here because the gallery uses the same tool as Binder for building the example (`repo2docker`).
So we need to tell pip to use `ipywidgets` 7.5 which adds support for `GridspecLayout`:

```
ipywidgets>=7.5,<8
```

**Comment by dhaitz** [comment]
Hi @jtpio, thanks for your suggestions! I've updated the requirements, added a binder badge and checked that it works.

**Comment by jtpio** [comment]
This looks good, thanks @dhaitz!

**Pull request merged**
