### PR TITLE
updating commit ref and GIF

### PR DESCRIPTION
**Pull request by cornhundred**
I updated the commit to a slightly updated version (which includes more categories). I also linked to a GIF, which is ~20MB - so feel free to not use the GIF if you think it is too large.

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @cornhundred for the update.

20MB is indeed quite large. Do you think it's possible to compress it a little bit?

I sometimes use the following `ffmpeg` command to convert a video into a gif (tweaking it or adjusting the scale might help):

`ffmpeg -i input.mp4 -r 20 -vf scale=1024:-1 output.gif`

**Comment by cornhundred** [comment]
Hi @jtpio I would like to add a different example to the Gallery (I haven't made a pull request), but I just wanted to check whether 1.6MB is too large for a GIF for the gallery: 

https://github.com/ismms-himc/visium-clustergrammer2/blob/working/img/visium-clustergrammer2_borderless_small.gif

**Comment by jtpio** [comment]
Thanks for the heads-up.

I suppose this is referring to https://github.com/voila-gallery/voila-gallery.github.io/pull/15?

**Comment by cornhundred** [comment]
Yeah, I'll make a small GIF here too

**Comment by jtpio** [comment]
Closing this PR since the public examples are now added to https://github.com/voila-gallery/voila-gallery.github.io.

Thanks again @cornhundred for all the contributions!

**Pull request closed without merging**
