### PR TITLE
Update design to new visual identity

### PR DESCRIPTION
**Pull request by SylvainCorlay**
- Using the new logos
- Updating the CSS to preserve screenshot's aspect ratio

localhost_8000_services_gallery(QuantStack)

The shadow of gallery items is removed on hover.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Ideally I would like to

- remove the **Launch** button to make the whole div a launch button (maybe with a transparent play button on hover)
- probably remove the **Source** button to be replaced with a github link in the corner...

**Comment by jtpio** [comment]
What about the logo in the README.md?

https://github.com/voila-gallery/gallery/blob/master/voila-gallery.svg

**Comment by jtpio** [comment]
> What about the logo in the README.md?

Using a markdown title "Voilà Gallery" with the new logo would be fine for now.

**Comment by SylvainCorlay** [comment]
Sure, that sounds good.

**Comment by jtpio** [comment]
> Ideally I would like to
> 
>     * remove the **Launch** button to make the whole div a launch button (maybe with a transparent play button on hover)
> 
>     * probably remove the **Source** button to be replaced with a github link in the corner...

Agree. We can iterate on it in a follow-up PR.

**Comment by SylvainCorlay** [comment]
:+1:

**Comment by jtpio** [comment]
Using the same colors as in the voila repo (to stay consistent).

image

Would be great to have a proper gallery logo in the future.

**Comment by SylvainCorlay** [comment]
> Would be great to have a proper gallery logo in the future.
>

Yes, I should ask the designer if she can iterate on this.

**Comment by jtpio** [comment]
Looks good, thanks @SylvainCorlay for this!

**Pull request merged**
